service: serverless-side-rendering

plugins:
  - serverless-plugin-chrome

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  timeout: 30 # optional, in seconds, default is 6

functions:
  render:
    handler: dist/handler.render
    events:
      - http:
          path: render
          method: get
          integration: lambda
          response:
            headers:
              Content-Type: "'text/html'"
            template: $input.path('$')
